#!/usr/bin/env bash

set -euo pipefail

go build -o pod-babashka-fswatcher main.go

if [[ "$WINDOWS" == "true" ]]; then
    mv pod-babashka-fswatcher pod-babashka-fswatcher.exe
fi

test/script.clj

cd watcher
go test
